### ISSUE TITLE
ReferenceError: psModule is not defined

### ISSUE THREAD

**Issue by alecmerdler** [ethul/purs-loader#110]
Looks like `psModule` is not being passed in [`bundle.js`](https://github.com/ethul/purs-loader/blob/78e2b0d91f5eb98674c5b05db0ef2c4f417581c0/src/bundle.js#L48).

**Console Output**
```
/home/alec/go/src/github.com/openshift/console/frontend/node_modules/purs-loader/lib/bundle.js:54
          psModule.emitError(errorMessage);
          ^
ReferenceError: psModule is not defined
    at ChildProcess.<anonymous> (/home/alec/go/src/github.com/openshift/console/frontend/node_modules/purs-loader/lib/bundle.js:54:11)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**webpack.config.ts**
```javascript
{
  test: /\.purs$/,
  loader: 'purs-loader',
  options: {
    psc: 'psa',
    src: ['node_modules/@purescript/**/*.purs', 'public/**/*.purs'],
    output: path.resolve(__dirname, 'public/dist'),
    bundleOutput: path.resolve(__dirname, 'public/dist'),
    bundle: true,
  }
},
```

Versions: 
`purs-loader@3.1.4`
`purescript@0.12.0`
`node@v8.9.1`

**Comment by alecmerdler** [comment]
@ethul I actually want to use this as a loader to integrate `purescript` into my project, will there be momentum if I open a PR for this issue?

**Comment by ethul** [comment]
A PR is most welcome. Thanks!
