### ISSUE TITLE
Webpack devserver crash with pscIde and parallel build

### ISSUE THREAD

**Issue by andys8** [ethul/purs-loader#155]
# Issue

I experience a crash when `pscIde` is set to `true`.

```
Compiling...
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:200:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

or

```
Error: ide client failed: purs: <socket: 38>: Data.ByteString.hGetLine: resource vanished (Connection reset by peer)
From previous event:
From previous event:
```

# Steps to Reproduce the Issue

1. Start a dev server with `pscIde: true`
1. It's working `"Compiled successfully!"`
1. Open an editor using `purescript-language-server` or `pscid`
1. Save an existing purescript file
1. Crash

It can be reproduced e.g. with this repository: https://github.com/andys8/create-react-app-purescript (`npm install && npm start`).

**Comment by andys8** [comment]
https://github.com/ethul/purs-loader/pull/157 merged and released
