### ISSUE TITLE
TypeError: Prelude['<<<'] is not a function1 bundle.js:928:12

### ISSUE THREAD

**Issue by haf** [ethul/purs-loader#22]
Greetings,

I'm trying to use this loader with https://github.com/paf31/purescript-thermite-todomvc and I'm getting pretty far, but not all the way: `TypeError: Prelude['<<<'] is not a function1 bundle.js:928:12` defined [here](https://github.com/purescript/purescript-prelude/blob/master/src/Prelude.purs#L130).

Output:

```
content is served from /Users/h/dev/logibit/cmdui
Hash: 087e6920a4b8c19c2912
Version: webpack 1.4.13
Time: 5708ms
    Asset   Size  Chunks             Chunk Names
bundle.js  94543       0  [emitted]  main
chunk    {0} bundle.js (main) 70290 [rendered]
    [0] ./src/index.js 81 {0} [built]
    [1] ./bower_components/purescript-prelude/src/Prelude.js 4448 {0} [built]
    [2] ./src/Main.purs 33 {0} [built]
    [3] ./build/Main/index.js 2603 {0} [built]
    [4] ./build/Thermite.Html.Elements/index.js 19438 {0} [built]
    [5] ./build/Thermite.Html/index.js 434 {0} [built]
    [6] ./build/Thermite.Events/index.js 2980 {0} [built]
    [7] ./build/Thermite.Action/index.js 5631 {0} [built]
    [8] ./build/Thermite/index.js 2107 {0} [built]
    [9] ./build/Thermite.Html.Attributes/index.js 8568 {0} [built]
   [10] ./build/Thermite.Types/index.js 455 {0} [built]
   [11] ./build/Thermite/foreign.js 1283 {0} [built]
   [12] ./build/Thermite.Internal/index.js 639 {0} [built]
   [13] ./build/Data.Monoid/index.js 1000 {0} [built]
   [14] ./build/Control.Monad.Eff/index.js 901 {0} [built]
   [15] ./build/Data.Maybe/index.js 10767 {0} [built]
   [16] ./build/DOM/index.js 71 {0} [built]
   [17] ./build/Thermite.Types/foreign.js 465 {0} [built]
   [18] ./build/Thermite.Internal/foreign.js 1284 {0} [built]
   [19] ./build/Control.Monad.Eff/foreign.js 946 {0} [built]
   [20] ./build/Data.Functor.Invariant/index.js 617 {0} [built]
   [21] ./build/Control.Alt/index.js 604 {0} [built]
   [22] ./build/Control.Alternative/index.js 739 {0} [built]
   [23] ./build/Control.Extend/index.js 1799 {0} [built]
   [24] ./build/Control.MonadPlus/index.js 1421 {0} [built]
   [25] ./build/Control.Plus/index.js 525 {0} [built]
   [26] ./build/Control.Lazy/index.js 451 {0} [built]
webpack: bundle is now VALID.
```

Config:

```
➜  cmdui git:(master) ✗ cat bower.json
{
  "name": "cmdui",
  "private": true,
  "devDependencies": {
    "purescript-prelude": "~0.1.0",
    "purescript-thermite": "^0.8.0",
    "purescript-arrays": "^0.4.0",
    "purescript-tuples": "^0.4.0",
    "purescript-lens": "master",
    "purescript-optic": "git@github.com:paf31/purescript-optic.git#0.7",
    "purescript-index": "git@github.com:paf31/purescript-index.git#0.7",
    "purescript-lists": "^0.7.0",
    "es5-shim": "~4.0.5"
  }
}
```

**Comment by ethul** [comment]
hi @haf, can you please provide the version of purescript, purs-loader, etc. that you are using?

**Comment by haf** [comment]
Yes; you can run it all yourself, it's OSS: https://github.com/haf/purescript-recq – it's all in the bower.json and package.json files.

**Comment by ethul** [comment]
Ah great. Thanks

**Comment by ethul** [comment]
I clone your repo and was able to get things to compile.

In purescript 0.7.x there is no `Debug.Trace` anymore. I had to change:
https://github.com/haf/purescript-recq/blob/master/src/ReCQ.purs#L4

to be

`import Control.Monad.Eff.Console`

Also, I am using webpack @ 1.10.1

And are you running purescript 0.7.1? `purs-loader@0.3.x` only supports purescript 0.7 and above.

**Comment by haf** [comment]
Yes, me too. The problem is when you do `npm start` and browse `localhost:8080` in the web dev console.

**Comment by ethul** [comment]
Ah okay. It should work if you remove the following line:
https://github.com/haf/purescript-recq/blob/master/webpack.config.js#L8

I know I had this in the example, but I think I should remove it too. I need to do some more investigation on when this line is necessary. In you case it is not needed.

Note that you will have to make React globally available on window in your app. Thermite expects it is global.

Hope this helps.

**Comment by haf** [comment]
Ok, so I got a simple [inc/dec counter sample to work](https://github.com/haf/purescript-recq/commit/a6079372e787721201d4059467789dbab0af2657)! Yey!

<img width="233" alt="screen shot 2015-07-19 at 22 59 02" src="https://cloud.githubusercontent.com/assets/193115/8767831/ca2112f6-2e69-11e5-8b6a-5578324d44c5.png">

 next up is the [full TODO](https://github.com/haf/purescript-recq/commit/ef9c7fe3a4fa7e0d06f04ecaf76f33a96cf7056e), which gives this error:

```
ERROR in ./src/Main.purs
Module build failed: Error: Compiling Main

Error:
Missing FFI implementations for module Main
See https://github.com/purescript/purescript/wiki/Error-Code-MissingFFIModule for more information, or to contribute content related to this error.


    at ChildProcess.<anonymous> (/Users/h/dev/logibit/cmdui/node_modules/purs-loader/index.js:2391:32)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
 @ ./src/index.js 2:17-39
```

**Comment by ethul** [comment]
I believe you just have to define your foreign imports in MainFFI.js. Since your webpack config defines the pattern *FFI.js

The purescript docs should give you an idea of how to define FFI.

**Comment by haf** [comment]
Sorry, I don't understand. The sample doesn't have any FFIs. The output says it has trouble compiling Prelude (see at the top of the listing):

```
Hash: 8f4206f556519e091009
Version: webpack 1.10.1
Time: 9791ms
    Asset    Size  Chunks             Chunk Names
bundle.js  635 kB       0  [emitted]  main
   [0] ./src/index.js 65 bytes {0} [built] [1 error]
    + 157 hidden modules

ERROR in ./src/Main.purs
Module build failed: Error: Compiling Prelude
Writing build/Prelude/index.js
Writing build/Prelude/foreign.js
Writing build/Prelude/externs.purs
Compiling Optic.Index.Types
Writing build/Optic.Index.Types/index.js
Writing build/Optic.Index.Types/externs.purs
Compiling Math
Writing build/Math/index.js
Writing build/Math/foreign.js
Writing build/Math/externs.purs
Compiling Data.Profunctor
Writing build/Data.Profunctor/index.js
Writing build/Data.Profunctor/externs.purs
Compiling Optic.Internal.Iso
Writing build/Optic.Internal.Iso/index.js
Writing build/Optic.Internal.Iso/externs.purs
Compiling Data.Monoid
Writing build/Data.Monoid/index.js
Writing build/Data.Monoid/externs.purs
Compiling Data.Int.Bits
Writing build/Data.Int.Bits/index.js
Writing build/Data.Int.Bits/foreign.js
Writing build/Data.Int.Bits/externs.purs
Compiling Data.Functor.Invariant
Writing build/Data.Functor.Invariant/index.js
Writing build/Data.Functor.Invariant/externs.purs
Compiling Data.Monoid.Endo
Writing build/Data.Monoid.Endo/index.js
Writing build/Data.Monoid.Endo/externs.purs
Compiling Data.Functor.Contravariant
Writing build/Data.Functor.Contravariant/index.js
Writing build/Data.Functor.Contravariant/externs.purs
Compiling Data.Predicate
Writing build/Data.Predicate/index.js
Writing build/Data.Predicate/externs.purs
Compiling Data.Functor
Writing build/Data.Functor/index.js
Writing build/Data.Functor/externs.purs
Compiling Data.Function
Writing build/Data.Function/index.js
Writing build/Data.Function/foreign.js
Writing build/Data.Function/externs.purs
Compiling Data.Comparison
Writing build/Data.Comparison/index.js
Writing build/Data.Comparison/externs.purs
Compiling Data.Equivalence
Writing build/Data.Equivalence/index.js
Writing build/Data.Equivalence/externs.purs
Compiling Data.Char
Writing build/Data.Char/index.js
Writing build/Data.Char/foreign.js
Writing build/Data.Char/externs.purs
Compiling Data.String.Unsafe
Writing build/Data.String.Unsafe/index.js
Writing build/Data.String.Unsafe/foreign.js
Writing build/Data.String.Unsafe/externs.purs
Compiling Data.Bifunctor
Writing build/Data.Bifunctor/index.js
Writing build/Data.Bifunctor/externs.purs
Compiling DOM.XHR
Writing build/DOM.XHR/index.js
Writing build/DOM.XHR/externs.purs
Compiling DOM.File
Writing build/DOM.File/index.js
Writing build/DOM.File/externs.purs
Compiling DOM
Writing build/DOM/index.js
Writing build/DOM/externs.purs
Compiling Control.Monad.Trans
Writing build/Control.Monad.Trans/index.js
Writing build/Control.Monad.Trans/externs.purs
Compiling Control.Monad.Error
Writing build/Control.Monad.Error/index.js
Writing build/Control.Monad.Error/externs.purs
Compiling Control.Monad.Eff
Writing build/Control.Monad.Eff/index.js
Writing build/Control.Monad.Eff/foreign.js
Writing build/Control.Monad.Eff/externs.purs
Compiling Control.Monad.Eff.Class
Writing build/Control.Monad.Eff.Class/index.js
Writing build/Control.Monad.Eff.Class/externs.purs
Compiling Control.Monad.Eff.Console
Writing build/Control.Monad.Eff.Console/index.js
Writing build/Control.Monad.Eff.Console/foreign.js
Writing build/Control.Monad.Eff.Console/externs.purs
Compiling Control.Monad.Eff.Unsafe
Writing build/Control.Monad.Eff.Unsafe/index.js
Writing build/Control.Monad.Eff.Unsafe/foreign.js
Writing build/Control.Monad.Eff.Unsafe/externs.purs
Compiling Control.Monad.ST
Writing build/Control.Monad.ST/index.js
Writing build/Control.Monad.ST/foreign.js
Writing build/Control.Monad.ST/externs.purs
Compiling Control.Monad.Cont.Trans
Writing build/Control.Monad.Cont.Trans/index.js
Writing build/Control.Monad.Cont.Trans/externs.purs
Compiling Control.Monad
Writing build/Control.Monad/index.js
Writing build/Control.Monad/externs.purs
Compiling Control.Lazy
Writing build/Control.Lazy/index.js
Writing build/Control.Lazy/externs.purs
Compiling Control.Extend
Writing build/Control.Extend/index.js
Writing build/Control.Extend/externs.purs
Compiling Control.Comonad
Writing build/Control.Comonad/index.js
Writing build/Control.Comonad/externs.purs
Compiling Control.Comonad.Trans
Writing build/Control.Comonad.Trans/index.js
Writing build/Control.Comonad.Trans/externs.purs
Compiling Data.Lazy
Writing build/Data.Lazy/index.js
Writing build/Data.Lazy/foreign.js
Writing build/Data.Lazy/externs.purs
Compiling Data.Monoid.Additive
Writing build/Data.Monoid.Additive/index.js
Writing build/Data.Monoid.Additive/externs.purs
Compiling Data.Monoid.Conj
Writing build/Data.Monoid.Conj/index.js
Writing build/Data.Monoid.Conj/externs.purs
Compiling Data.Monoid.Disj
Writing build/Data.Monoid.Disj/index.js
Writing build/Data.Monoid.Disj/externs.purs
Compiling Data.Monoid.Dual
Writing build/Data.Monoid.Dual/index.js
Writing build/Data.Monoid.Dual/externs.purs
Compiling Data.Monoid.Multiplicative
Writing build/Data.Monoid.Multiplicative/index.js
Writing build/Data.Monoid.Multiplicative/externs.purs
Compiling Control.Bind
Writing build/Control.Bind/index.js
Writing build/Control.Bind/externs.purs
Compiling Control.Biapply
Writing build/Control.Biapply/index.js
Writing build/Control.Biapply/externs.purs
Compiling Control.Biapplicative
Writing build/Control.Biapplicative/index.js
Writing build/Control.Biapplicative/externs.purs
Compiling Data.Bifunctor.Clown
Writing build/Data.Bifunctor.Clown/index.js
Writing build/Data.Bifunctor.Clown/externs.purs
Compiling Data.Bifunctor.Flip
Writing build/Data.Bifunctor.Flip/index.js
Writing build/Data.Bifunctor.Flip/externs.purs
Compiling Data.Bifunctor.Join
Writing build/Data.Bifunctor.Join/index.js
Writing build/Data.Bifunctor.Join/externs.purs
Compiling Data.Bifunctor.Joker
Writing build/Data.Bifunctor.Joker/index.js
Writing build/Data.Bifunctor.Joker/externs.purs
Compiling Data.Bifunctor.Product
Writing build/Data.Bifunctor.Product/index.js
Writing build/Data.Bifunctor.Product/externs.purs
Compiling Data.Bifunctor.Wrap
Writing build/Data.Bifunctor.Wrap/index.js
Writing build/Data.Bifunctor.Wrap/externs.purs
Compiling Control.Apply
Writing build/Control.Apply/index.js
Writing build/Control.Apply/externs.purs
Compiling Data.Bifoldable
Writing build/Data.Bifoldable/index.js
Writing build/Data.Bifoldable/externs.purs
Compiling Data.Bitraversable
Writing build/Data.Bitraversable/index.js
Writing build/Data.Bitraversable/externs.purs
Compiling Control.Alt
Writing build/Control.Alt/index.js
Writing build/Control.Alt/externs.purs
Compiling Control.Plus
Writing build/Control.Plus/index.js
Writing build/Control.Plus/externs.purs
Compiling Control.Alternative
Writing build/Control.Alternative/index.js
Writing build/Control.Alternative/externs.purs
Compiling Control.MonadPlus
Writing build/Control.MonadPlus/index.js
Writing build/Control.MonadPlus/externs.purs
Compiling Data.Maybe
Writing build/Data.Maybe/index.js
Writing build/Data.Maybe/externs.purs
Compiling Data.Array.ST
Writing build/Data.Array.ST/index.js
Writing build/Data.Array.ST/foreign.js
Writing build/Data.Array.ST/externs.purs
Compiling Data.Int
Writing build/Data.Int/index.js
Writing build/Data.Int/foreign.js
Writing build/Data.Int/externs.purs
Compiling Data.Maybe.First
Writing build/Data.Maybe.First/index.js
Writing build/Data.Maybe.First/externs.purs
Compiling Data.Maybe.Last
Writing build/Data.Maybe.Last/index.js
Writing build/Data.Maybe.Last/externs.purs
Compiling Data.Foldable
Writing build/Data.Foldable/index.js
Writing build/Data.Foldable/foreign.js
Writing build/Data.Foldable/externs.purs
Compiling Data.Maybe.Unsafe
Writing build/Data.Maybe.Unsafe/index.js
Writing build/Data.Maybe.Unsafe/externs.purs
Compiling Data.StrMap.ST
Writing build/Data.StrMap.ST/index.js
Writing build/Data.StrMap.ST/foreign.js
Writing build/Data.StrMap.ST/externs.purs
Compiling Data.String
Writing build/Data.String/index.js
Writing build/Data.String/foreign.js
Writing build/Data.String/externs.purs
Compiling Data.String.Regex
Writing build/Data.String.Regex/index.js
Writing build/Data.String.Regex/foreign.js
Writing build/Data.String.Regex/externs.purs
Compiling Data.Traversable
Writing build/Data.Traversable/index.js
Writing build/Data.Traversable/foreign.js
Writing build/Data.Traversable/externs.purs
Compiling Data.Const
Writing build/Data.Const/index.js
Writing build/Data.Const/externs.purs
Compiling Data.Either
Writing build/Data.Either/index.js
Writing build/Data.Either/externs.purs
Compiling Data.Either.Nested
Writing build/Data.Either.Nested/index.js
Writing build/Data.Either.Nested/externs.purs
Compiling Data.Either.Unsafe
Writing build/Data.Either.Unsafe/index.js
Writing build/Data.Either.Unsafe/externs.purs
Compiling Data.Profunctor.Choice
Writing build/Data.Profunctor.Choice/index.js
Writing build/Data.Profunctor.Choice/externs.purs
Compiling Optic.Internal.Prism
Writing build/Optic.Internal.Prism/index.js
Writing build/Optic.Internal.Prism/externs.purs
Compiling Data.Identity
Writing build/Data.Identity/index.js
Writing build/Data.Identity/externs.purs
Compiling Control.Monad.Rec.Class
Writing build/Control.Monad.Rec.Class/index.js
Writing build/Control.Monad.Rec.Class/externs.purs
Compiling Control.Monad.Except.Trans
Writing build/Control.Monad.Except.Trans/index.js
Writing build/Control.Monad.Except.Trans/externs.purs
Compiling Control.Monad.Except
Writing build/Control.Monad.Except/index.js
Writing build/Control.Monad.Except/externs.purs
Compiling Data.Distributive
Writing build/Data.Distributive/index.js
Writing build/Data.Distributive/externs.purs
Compiling Control.Monad.Reader.Trans
Writing build/Control.Monad.Reader.Trans/index.js
Writing build/Control.Monad.Reader.Trans/externs.purs
Compiling Control.Monad.Reader
Writing build/Control.Monad.Reader/index.js
Writing build/Control.Monad.Reader/externs.purs
Compiling Data.Tagged
Writing build/Data.Tagged/index.js
Writing build/Data.Tagged/externs.purs
Compiling Optic.Internal.Setter
Writing build/Optic.Internal.Setter/index.js
Writing build/Optic.Internal.Setter/externs.purs
Compiling Optic.Types
Writing build/Optic.Types/index.js
Writing build/Optic.Types/externs.purs
Compiling Optic.Getter
Writing build/Optic.Getter/index.js
Writing build/Optic.Getter/externs.purs
Compiling Optic.Lens
Writing build/Optic.Lens/index.js
Writing build/Optic.Lens/externs.purs
Compiling Optic.Types.Extended
Writing build/Optic.Types.Extended/index.js
Writing build/Optic.Types.Extended/externs.purs
Compiling Optic.Equality
Writing build/Optic.Equality/index.js
Writing build/Optic.Equality/externs.purs
Compiling Optic.Traversal
Writing build/Optic.Traversal/index.js
Writing build/Optic.Traversal/externs.purs
Compiling Data.Tuple
Writing build/Data.Tuple/index.js
Writing build/Data.Tuple/externs.purs
Compiling Control.Comonad.Env.Trans
Writing build/Control.Comonad.Env.Trans/index.js
Writing build/Control.Comonad.Env.Trans/externs.purs
Compiling Control.Comonad.Env
Writing build/Control.Comonad.Env/index.js
Writing build/Control.Comonad.Env/externs.purs
Compiling Control.Comonad.Env.Class
Writing build/Control.Comonad.Env.Class/index.js
Writing build/Control.Comonad.Env.Class/externs.purs
Compiling Control.Comonad.Store.Trans
Writing build/Control.Comonad.Store.Trans/index.js
Writing build/Control.Comonad.Store.Trans/externs.purs
Compiling Control.Comonad.Store
Writing build/Control.Comonad.Store/index.js
Writing build/Control.Comonad.Store/externs.purs
Compiling Control.Comonad.Store.Class
Writing build/Control.Comonad.Store.Class/index.js
Writing build/Control.Comonad.Store.Class/externs.purs
Compiling Control.Comonad.Traced.Trans
Writing build/Control.Comonad.Traced.Trans/index.js
Writing build/Control.Comonad.Traced.Trans/externs.purs
Compiling Control.Comonad.Traced
Writing build/Control.Comonad.Traced/index.js
Writing build/Control.Comonad.Traced/externs.purs
Compiling Control.Comonad.Traced.Class
Writing build/Control.Comonad.Traced.Class/index.js
Writing build/Control.Comonad.Traced.Class/externs.purs
Compiling Control.Monad.Error.Trans
Writing build/Control.Monad.Error.Trans/index.js
Writing build/Control.Monad.Error.Trans/externs.purs
Compiling Control.Monad.Maybe.Trans
Writing build/Control.Monad.Maybe.Trans/index.js
Writing build/Control.Monad.Maybe.Trans/externs.purs
Compiling Control.Monad.RWS.Trans
Writing build/Control.Monad.RWS.Trans/index.js
Writing build/Control.Monad.RWS.Trans/externs.purs
Compiling Control.Monad.RWS
Writing build/Control.Monad.RWS/index.js
Writing build/Control.Monad.RWS/externs.purs
Compiling Control.Monad.State.Trans
Writing build/Control.Monad.State.Trans/index.js
Writing build/Control.Monad.State.Trans/externs.purs
Compiling Control.Monad.State
Writing build/Control.Monad.State/index.js
Writing build/Control.Monad.State/externs.purs
Compiling Optic.Monad
Writing build/Optic.Monad/index.js
Writing build/Optic.Monad/externs.purs
Compiling Control.Monad.Writer.Trans
Writing build/Control.Monad.Writer.Trans/index.js
Writing build/Control.Monad.Writer.Trans/externs.purs
Compiling Control.Monad.Cont.Class
Writing build/Control.Monad.Cont.Class/index.js
Writing build/Control.Monad.Cont.Class/externs.purs
Compiling Control.Monad.Error.Class
Writing build/Control.Monad.Error.Class/index.js
Writing build/Control.Monad.Error.Class/externs.purs
Compiling Control.Monad.Reader.Class
Writing build/Control.Monad.Reader.Class/index.js
Writing build/Control.Monad.Reader.Class/externs.purs
Compiling Control.Monad.State.Class
Writing build/Control.Monad.State.Class/index.js
Writing build/Control.Monad.State.Class/externs.purs
Compiling Optic.Monad.Getter
Writing build/Optic.Monad.Getter/index.js
Writing build/Optic.Monad.Getter/externs.purs
Compiling Optic.Review
Writing build/Optic.Review/index.js
Writing build/Optic.Review/externs.purs
Compiling Control.Monad.Writer
Writing build/Control.Monad.Writer/index.js
Writing build/Control.Monad.Writer/externs.purs
Compiling Control.Monad.Writer.Class
Writing build/Control.Monad.Writer.Class/index.js
Writing build/Control.Monad.Writer.Class/externs.purs
Compiling Control.Monad.RWS.Class
Writing build/Control.Monad.RWS.Class/index.js
Writing build/Control.Monad.RWS.Class/externs.purs
Compiling Data.Array
Writing build/Data.Array/index.js
Writing build/Data.Array/foreign.js
Writing build/Data.Array/externs.purs
Compiling Data.Array.Unsafe
Writing build/Data.Array.Unsafe/index.js
Writing build/Data.Array.Unsafe/foreign.js
Writing build/Data.Array.Unsafe/externs.purs
Compiling Data.Profunctor.Strong
Writing build/Data.Profunctor.Strong/index.js
Writing build/Data.Profunctor.Strong/externs.purs
Compiling Data.Tuple.Nested
Writing build/Data.Tuple.Nested/index.js
Writing build/Data.Tuple.Nested/externs.purs
Compiling Data.Unfoldable
Writing build/Data.Unfoldable/index.js
Writing build/Data.Unfoldable/externs.purs
Compiling Control.Monad.List.Trans
Writing build/Control.Monad.List.Trans/index.js
Writing build/Control.Monad.List.Trans/externs.purs
Compiling Data.Enum
Writing build/Data.Enum/index.js
Writing build/Data.Enum/externs.purs
Compiling Data.List
Writing build/Data.List/index.js
Writing build/Data.List/externs.purs
Compiling Data.List.Unsafe
Writing build/Data.List.Unsafe/index.js
Writing build/Data.List.Unsafe/externs.purs
Compiling Data.Map
Writing build/Data.Map/index.js
Writing build/Data.Map/externs.purs
Compiling Data.Set
Writing build/Data.Set/index.js
Writing build/Data.Set/externs.purs
Compiling Data.StrMap
Writing build/Data.StrMap/index.js
Writing build/Data.StrMap/foreign.js
Writing build/Data.StrMap/externs.purs
Compiling Data.StrMap.ST.Unsafe
Writing build/Data.StrMap.ST.Unsafe/index.js
Writing build/Data.StrMap.ST.Unsafe/foreign.js
Writing build/Data.StrMap.ST.Unsafe/externs.purs
Compiling Data.StrMap.Unsafe
Writing build/Data.StrMap.Unsafe/index.js
Writing build/Data.StrMap.Unsafe/foreign.js
Writing build/Data.StrMap.Unsafe/externs.purs
Compiling ReCQ
Writing build/ReCQ/index.js
Writing build/ReCQ/externs.purs
Compiling Data.List.Lazy
Writing build/Data.List.Lazy/index.js
Writing build/Data.List.Lazy/externs.purs
Compiling Data.List.ZipList
Writing build/Data.List.ZipList/index.js
Writing build/Data.List.ZipList/externs.purs
Compiling Optic.Fold
Writing build/Optic.Fold/index.js
Writing build/Optic.Fold/externs.purs
Compiling Optic.Index.Class
Writing build/Optic.Index.Class/index.js
Writing build/Optic.Index.Class/externs.purs
Compiling Optic.Contains
Writing build/Optic.Contains/index.js
Writing build/Optic.Contains/externs.purs
Compiling Optic.Index
Writing build/Optic.Index/index.js
Writing build/Optic.Index/externs.purs
Compiling Optic.At
Writing build/Optic.At/index.js
Writing build/Optic.At/externs.purs
Compiling Optic.Iso
Writing build/Optic.Iso/index.js
Writing build/Optic.Iso/externs.purs
Compiling Optic.Prism
Writing build/Optic.Prism/index.js
Writing build/Optic.Prism/externs.purs
Compiling Optic.Setter
Writing build/Optic.Setter/index.js
Writing build/Optic.Setter/externs.purs
Compiling Optic.Core
Writing build/Optic.Core/index.js
Writing build/Optic.Core/externs.purs
Compiling Optic.Laws.Lens
Writing build/Optic.Laws.Lens/index.js
Writing build/Optic.Laws.Lens/externs.purs
Compiling Optic.Monad.Setter
Writing build/Optic.Monad.Setter/index.js
Writing build/Optic.Monad.Setter/externs.purs
Compiling Optic.Extended
Writing build/Optic.Extended/index.js
Writing build/Optic.Extended/externs.purs
Compiling Thermite.Types
Writing build/Thermite.Types/index.js
Writing build/Thermite.Types/foreign.js
Writing build/Thermite.Types/externs.purs
Compiling Thermite.Internal
Writing build/Thermite.Internal/index.js
Writing build/Thermite.Internal/foreign.js
Writing build/Thermite.Internal/externs.purs
Compiling Thermite.Action
Writing build/Thermite.Action/index.js
Writing build/Thermite.Action/externs.purs
Compiling Thermite.Events
Writing build/Thermite.Events/index.js
Writing build/Thermite.Events/externs.purs
Compiling Thermite.Html
Writing build/Thermite.Html/index.js
Writing build/Thermite.Html/externs.purs
Compiling Thermite
Writing build/Thermite/index.js
Writing build/Thermite/foreign.js
Writing build/Thermite/externs.purs
Compiling Thermite.Html.Attributes
Writing build/Thermite.Html.Attributes/index.js
Writing build/Thermite.Html.Attributes/externs.purs
Compiling Thermite.Html.Attributes.Unsafe
Writing build/Thermite.Html.Attributes.Unsafe/index.js
Writing build/Thermite.Html.Attributes.Unsafe/foreign.js
Writing build/Thermite.Html.Attributes.Unsafe/externs.purs
Compiling Thermite.Html.Elements
Writing build/Thermite.Html.Elements/index.js
Writing build/Thermite.Html.Elements/externs.purs
Compiling Main

Error:
Missing FFI implementations for module Main
See https://github.com/purescript/purescript/wiki/Error-Code-MissingFFIModule for more information, or to contribute content related to this error.


    at ChildProcess.<anonymous> (/Users/h/dev/logibit/cmdui/node_modules/purs-loader/index.js:2391:32)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
 @ ./src/index.js 2:17-39
```

I've grepped https://github.com/paf31/purescript-thermite-todomvc for their FFIs but I can't find any differences except they have a Main.js -- however that Main.js doesn't define any FFIs nor is it referenced anywhere in the build files...

**Comment by ethul** [comment]
I was referring to the foreign imports:
https://github.com/haf/purescript-recq/blob/ef9c7fe3a4fa7e0d06f04ecaf76f33a96cf7056e/src/Main.purs#L80-84

These need corresponding FFI implementations. For example you can define them in `MainFFI.js`.

There is an example of this in the `purs-loader` repo:
https://github.com/ethul/purs-loader/blob/master/example/src/TestFFI.js

Hope this helps.

**Comment by ethul** [comment]
Closing for now. Please reopen if the issue still persists.
