### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'src' of undefined

### ISSUE THREAD

**Issue by ethul** [ethul/purs-loader#60]
Refers to [line 149](https://github.com/ethul/purs-loader/blob/7243be70a2163be2230a5f2739768137305a24ef/src/index.js#L149)

**Comment by julien-truffaut** [comment]
@ethul I am getting the same error, what should I do to resolve it?

**Comment by ethul** [comment]
Thanks for the heads up on this issue. What version of the loader are you
using?

**Comment by ethul** [comment]
P.S. - your monocle library is awesome!

**Comment by julien-truffaut** [comment]
Thanks :)

I use ^2.0.0-rc.1

**Comment by ethul** [comment]
Thanks for the info. I thought that issue was resolved in 2.0.0-rc.1, but
looks like it is not fixed yet. Are you able to provide a stack trace or
any details from the error output?

**Comment by julien-truffaut** [comment]
Sure, this is what I get when I run `npm run webpack:server` (from https://github.com/ethul/purescript-webpack-example)

```
ERROR in ./src/Main.purs
Module build failed: TypeError: Cannot read property 'src' of undefined
    at /Users/julien/Project/typology/node_modules/purs-loader/lib/index.js:176:67
    at String.replace (native)
    at /Users/julien/Project/typology/node_modules/purs-loader/lib/index.js:175:22
    at tryCatcher (/Users/julien/Project/typology/node_modules/purs-loader/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/julien/Project/typology/node_modules/purs-loader/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/julien/Project/typology/node_modules/purs-loader/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/julien/Project/typology/node_modules/purs-loader/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/julien/Project/typology/node_modules/purs-loader/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/julien/Project/typology/node_modules/purs-loader/node_modules/bluebird/js/release/promise.js:636:18)
    at PropertiesPromiseArray.PromiseArray._resolve (/Users/julien/Project/typology/node_modules/purs-loader/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PropertiesPromiseArray._promiseFulfilled (/Users/julien/Project/typology/node_modules/purs-loader/node_modules/bluebird/js/release/props.js:78:14)
    at Promise._settlePromise (/Users/julien/Project/typology/node_modules/purs-loader/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/julien/Project/typology/node_modules/purs-loader/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/julien/Project/typology/node_modules/purs-loader/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/julien/Project/typology/node_modules/purs-loader/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Users/julien/Project/typology/node_modules/purs-loader/node_modules/bluebird/js/release/promise.js:431:57)
 @ ./src/entry.js 1:0-22
```

**Comment by ethul** [comment]
Thanks. I will dig into this when I am back to my computer. However, it
might be worth trying to remove your bower_components directory and running
bower install again. Most likely won't change anything, but could be worth
a quick try.

**Comment by julien-truffaut** [comment]
I tried but the error persists. Please tell me if I can be of any help.

**Comment by ethul** [comment]
Thanks for giving it a try. I will look into this further and keep you
posted.

**Comment by ethul** [comment]
I just gave this a try. The `purescript-webpack-example` seemed to build for me.

But I just wanted to check if you are having an issue specifically with the `purescript-webpack-example` or if you are getting this error on a different project. If the error is cropping up on a different project, are you able to provide the webpack config?

Thanks!

**Comment by julien-truffaut** [comment]
The original `purescript-webpack-example` is fine. It is after I added an example with halogen that I got this error. I am new to purescript, so I might have done something stupid but I believe the webpack config is identical to `purescript-webpack-example`.

Here is the project I am working on if it can help: https://github.com/julien-truffaut/typology/blob/master/webpack.config.js

**Comment by ethul** [comment]
Thanks for the link to the config.

I think you just have to add the path to the source file of your project on [line 17](https://github.com/julien-truffaut/typology/blob/4389449f9a1ae6731cde2512e2549c0d53b973c0/webpack.config.js#L17).

Instead of 

```javascript
src: [ 'bower_components/purescript-*/src/**/*.purs', 'src/Example/**/*.purs' ]
```

Please give the following a try

```javascript
src: [ 'bower_components/purescript-*/src/**/*.purs', 'src/*.purs' ]
```

Let me know how it goes.

**Comment by julien-truffaut** [comment]
Thanks @ethul! Sorry for the noise ... I don't really understand how it worked at some point as I never had a `Example` directory.

**Comment by ethul** [comment]
Glad it worked!
