### ISSUE TITLE
webpack tests not working

### ISSUE THREAD

**Issue by buscarini** [ethul/purs-loader#81]
Sorry if this is not the place to ask this, but I don't have much experience this. I have started a project with an electron boilerplate that uses webpack; all js, and I wanted to start using Purescript for some parts of it. I have managed to get the app to run, but I haven't been able to figure out how to make the tests run.

This is my config:

`{
        test: /\.purs$/,
        loader: 'purs',
		exclude: /node_modules/,
		query: {
			psc: 'psc',
			src: ['bower_components/purescript-*/src/**/*.purs', 'app/**/*.purs']
		}
	},`

And this is the output with the error:

> OneModel@1.0.0 test /Users/josanchez/prog/swiftmodel/electron
> cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=test mocha --compilers js:babel-register --recursive --require ./test/setup.js test/**/*.spec.js

/Users/josanchez/prog/swiftmodel/electron/app/utils/types.js:20
	"char": $foreign["char"],
	        ^

ReferenceError: $foreign is not defined
    at Object.<anonymous> (/Users/josanchez/prog/swiftmodel/electron/app/utils/types.js:3:1)
    at Module._compile (module.js:573:32)
    at loader (/Users/josanchez/prog/swiftmodel/electron/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/josanchez/prog/swiftmodel/electron/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/josanchez/prog/swiftmodel/electron/app/reducers/entities.js:23:1)
    at Module._compile (module.js:573:32)
    at loader (/Users/josanchez/prog/swiftmodel/electron/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/josanchez/prog/swiftmodel/electron/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/josanchez/prog/swiftmodel/electron/test/reducers/entities.spec.js:2:1)
    at Module._compile (module.js:573:32)
    at loader (/Users/josanchez/prog/swiftmodel/electron/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/josanchez/prog/swiftmodel/electron/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /Users/josanchez/prog/swiftmodel/electron/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/josanchez/prog/swiftmodel/electron/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/Users/josanchez/prog/swiftmodel/electron/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/Users/josanchez/prog/swiftmodel/electron/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

Thanks

**Comment by ethul** [comment]
I am happy to help out if I can. It looks like you're running your tests with `mocha`. Are you importing purescript files from your test files? If so, then I think webpack would have to be pre-processing the test files before they are run. I just did a quick search and there is a project that might do this: https://github.com/zinserjan/mocha-webpack. But maybe this is not what you're looking for. Just a thought!

**Comment by buscarini** [comment]
Thanks! Yes, I'm importing one js file from the test files, and that file imports the purescript files. I'll check later and report back

**Comment by ethul** [comment]
Welcome!

**Comment by buscarini** [comment]
It worked! I had to fight a bit with it but at the end I managed to get it working. Thanks very much

**Comment by ethul** [comment]
Welcome. Glad it works!
