### ISSUE TITLE
Trouble with monorepos

### ISSUE THREAD

**Issue by bkonkle** [ethul/purs-loader#85]
I'm using a monorepo managed by [Lerna](https://github.com/lerna/lerna), and having trouble because of [this line](https://github.com/ethul/purs-loader/blob/master/src/index.js#L114).

My project setup looks like this:

```
peerdrop/
├── packages/
│   ├── peerdrop-core/
│   │   └── package.json
│   ├── peerdrop-desktop/
│   │   └── package.json
│   ├── peerdrop-mobile/
│   │   └── package.json
│   └── peerdrop-web/
│       └── package.json
└── package.json
```

I'm getting errors like this from Webpack 2:

```
ERROR in ../peerdrop-core/src/Types.purs
Module build failed: Error: ENOENT: no such file or directory, open '/Users/brandon/code/the-universe/packages/peerdrop-web/output/Types/index.js'
    at toJavaScript (/Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/purs-loader/lib/index.js:202:12)
    at /Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/purs-loader/lib/index.js:162:16
From previous event:
    at /Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/purs-loader/lib/index.js:160:22
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Object.purescriptLoader (/Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/purs-loader/lib/index.js:159:8)
 @ ../peerdrop-core/src/Main.js 13:16-39
 @ ./src/Main.js
 @ multi babel-polyfill ./src/Main.js webpack/hot/only-dev-server

ERROR in ../peerdrop-core/src/State/Store.purs
Module build failed: Error: purs-loader failed
    at /Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/purs-loader/lib/index.js:167:32
    at Array.forEach (native)
    at /Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/purs-loader/lib/index.js:166:31
    at tryCatcher (/Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
 @ ../peerdrop-core/src/Main.js 11:16-45
 @ ./src/Main.js
 @ multi babel-polyfill ./src/Main.js webpack/hot/only-dev-server
```

It's looking for `peerdrop-core/src/Types.purs` in `peerdrop-web/output/Types/index.js`, because it's only looking for `output` in the `peerdrop-web` package.

I'm checking out the project and experimenting with some ideas on how to work around this now. Let me know if you have any ideas!

**Comment by bkonkle** [comment]
The value of `this.resourcePath` when that line is called is this: `/Users/brandon/code/the-universe/packages/peerdrop-core/src/Types.purs`.

This gives me a couple of different options to try to find the output directory. The most reliable is probably to use `findup` to find the nearest `package.json`, and then look for `output` there. How do I make sure the compilation output goes to the correct `output` folder depending on the package that it comes from, though?

**Comment by bkonkle** [comment]
Or, am I looking at this the wrong way? Should it actually be compiled to `peerdrop-web`'s `output` directory since it's being compiled _for_ that package?

**Comment by bkonkle** [comment]
Okay! Solved the first error by adding a `bower.json` file at the root of the `peerdrop-web` package.

Next up:

```
ERROR in ../peerdrop-core/src/State/Store.purs
Module build failed: TypeError: Cannot read property 'src' of undefined
    at /Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/purs-loader/lib/index.js:214:67
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at /Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/purs-loader/lib/index.js:213:22
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
From previous event:
    at toJavaScript (/Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/purs-loader/lib/index.js:204:6)
    at /Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/purs-loader/lib/index.js:162:16
From previous event:
    at /Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/purs-loader/lib/index.js:160:22
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Object.purescriptLoader (/Users/brandon/code/the-universe/packages/peerdrop-web/node_modules/purs-loader/lib/index.js:159:8)
 @ ../peerdrop-core/src/Main.js 11:16-45
 @ ./src/Main.js
 @ multi babel-polyfill ./src/Main.js webpack/hot/only-dev-server
```

**Comment by bkonkle** [comment]
Ah - I'm getting stuff that's not showing up in the module map for some reason. Here's the result of some logging in the toJavaScript function:

```
p1 -> Data.Maybe
result.psModuleMap[p1] -> undefined
p1 -> Prelude
result.psModuleMap[p1] -> undefined
p1 -> State.User
result.psModuleMap[p1] -> { src: '/Users/brandon/code/the-universe/packages/peerdrop-core/src/State/User.purs' }
p1 -> Redux.Mini
result.psModuleMap[p1] -> undefined
```

This apparently means it's finding things in `peerdrop-core/src`, but not `peerdrop-core/bower_components`. My `src` config looks like this:

```js
    src: [
      'src/**/*.purs',
      'bower_components/purescript-*/src/**/*.purs',
      '../peerdrop-core/src/**/*.purs',
      '../peerdrop-core/bower_components/purescript-*/src/**/*.purs',
    ],
```

**Comment by bkonkle** [comment]
Solved! I had to take two steps to correct the issue:

* Add a `bower.json` to the `peerdrop-web` package
* Make the query on my purs-loader definition look like this:

```js
        "query": {
          "psc": "psa",
          "warnings": false,
          "src": [
            "src/**/*.purs",
            "bower_components/purescript-*/src/**/*.purs",
            "/Users/brandon/code/the-universe/packages/peerdrop-core/src/**/*.purs",
            "/Users/brandon/code/the-universe/packages/peerdrop-core/bower_components/purescript-*/src/**/*.purs"
          ]
        }
```

Now things are compiling smoothly! Woo!

**Comment by ethul** [comment]
Glad this is working! I wonder if in some capacity this should be added to
the README in a troubleshooting section. I have added this section already
in the beta version:
https://github.com/ethul/purs-loader/tree/topic/error-handling#troubleshooting

What do you think? Could there be something to add here for the issue you
solved?
